development:
  adapter: mysql 
  database: outlaws_dev
  username: outlaws
  password: softball2005
  host: localhost

test: &test
  adapter: mysql 
  database: outlaws_test
  username: outlaws
  password: softball2005
  host: localhost

production:
  adapter: mysql 
  database: outlaws_prod
  username: outlaws
  password: softball2005
  host: localhost

cucumber:
  <<: *test
